// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter blog title
   * - **API ID Path**: blog_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Publish Date field in *Blog Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.publish_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  publish_date: prismic.DateField;

  /**
   * Category field in *Blog Post*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select Category
   * - **API ID Path**: blog_post.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  category: prismic.SelectField<
    | "Market Trends"
    | "Real Estate Guide"
    | "Investment"
    | "Lifestyle"
    | "Company News"
  >;

  /**
   * Author field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Admin
   * - **API ID Path**: blog_post.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author: prismic.KeyTextField;

  /**
   * Banner Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Short Excerpt field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A short summary for the blog card
   * - **API ID Path**: blog_post.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  excerpt: prismic.KeyTextField;

  /**
   * Content field in *Blog Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Write your blog post here...
   * - **API ID Path**: blog_post.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField; /**
   * Meta Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: SEO Title
   * - **API ID Path**: blog_post.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Brief summary for search engines
   * - **API ID Path**: blog_post.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Keywords field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Comma separated keywords
   * - **API ID Path**: blog_post.keywords
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  keywords: prismic.KeyTextField;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blog_post",
    Lang
  >;

type PageDocumentDataSlicesSlice = never;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title shown in search results
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Description shown in search results
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Property → Amenities*
 */
export interface PropertyDocumentDataAmenitiesItem {
  /**
   * Amenity Name field in *Property → Amenities*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Swimming Pool
   * - **API ID Path**: property.amenities[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;
}

/**
 * Item in *Property → Image Gallery*
 */
export interface PropertyDocumentDataGalleryItem {
  /**
   * Photo field in *Property → Image Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: property.gallery[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Content for Property documents
 */
interface PropertyDocumentData {
  /**
   * Property Name field in *Property*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Akshar Oceanis
   * - **API ID Path**: property.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Category field in *Property*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select Category
   * - **API ID Path**: property.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  category: prismic.SelectField<
    "Residential" | "Commercial" | "Industrial" | "Agricultural"
  >;

  /**
   * Property Type field in *Property*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select Type
   * - **API ID Path**: property.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  type: prismic.SelectField<
    | "Apartment"
    | "Villa"
    | "Plot"
    | "Office"
    | "Shop"
    | "Warehouse"
    | "Farmhouse"
  >;

  /**
   * Status field in *Property*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select Status
   * - **API ID Path**: property.status
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  status: prismic.SelectField<
    "For Sale" | "For Rent" | "Under Construction" | "Ready to Move"
  >;

  /**
   * Price field in *Property*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Numerical value
   * - **API ID Path**: property.price
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  price: prismic.NumberField;

  /**
   * Price on Request field in *Property*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: property.price_on_request
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  price_on_request: prismic.BooleanField;

  /**
   * Main Featured Image field in *Property*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: property.main_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  main_image: prismic.ImageField<never>;

  /**
   * Short Description field in *Property*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Brief summary for the card view
   * - **API ID Path**: property.short_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  short_description: prismic.KeyTextField;

  /**
   * Full Description field in *Property*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Detailed description of the property
   * - **API ID Path**: property.full_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  full_description: prismic.RichTextField;

  /**
   * Show on Home Page field in *Property*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: property.is_featured
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_featured: prismic.BooleanField; /**
   * Location Name field in *Property*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Science City, Ahmedabad
   * - **API ID Path**: property.location
   * - **Tab**: Details
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  location: prismic.KeyTextField;

  /**
   * Full Address field in *Property*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: property.address
   * - **Tab**: Details
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  address: prismic.KeyTextField;

  /**
   * Area (Sq.Ft) field in *Property*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: property.area
   * - **Tab**: Details
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  area: prismic.NumberField;

  /**
   * Configuration field in *Property*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. 3 BHK, 4 BHK
   * - **API ID Path**: property.configuration
   * - **Tab**: Details
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  configuration: prismic.KeyTextField;

  /**
   * Possession Status field in *Property*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Ready to Move
   * - **API ID Path**: property.possession_status
   * - **Tab**: Details
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  possession_status: prismic.KeyTextField;

  /**
   * Possession Date field in *Property*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: property.possession_date
   * - **Tab**: Details
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  possession_date: prismic.DateField;

  /**
   * Amenities field in *Property*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: property.amenities[]
   * - **Tab**: Details
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  amenities: prismic.GroupField<Simplify<PropertyDocumentDataAmenitiesItem>>;

  /**
   * Image Gallery field in *Property*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: property.gallery[]
   * - **Tab**: Details
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  gallery: prismic.GroupField<Simplify<PropertyDocumentDataGalleryItem>>; /**
   * Meta Title field in *Property*
   *
   * - **Field Type**: Text
   * - **Placeholder**: SEO Title
   * - **API ID Path**: property.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Property*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Brief summary for search engines
   * - **API ID Path**: property.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Keywords field in *Property*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Comma separated keywords
   * - **API ID Path**: property.keywords
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  keywords: prismic.KeyTextField;
}

/**
 * Property document from Prismic
 *
 * - **API ID**: `property`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PropertyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PropertyDocumentData>,
    "property",
    Lang
  >;

export type AllDocumentTypes =
  | BlogPostDocument
  | PageDocument
  | PropertyDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogPostDocument,
      BlogPostDocumentData,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PropertyDocument,
      PropertyDocumentData,
      PropertyDocumentDataAmenitiesItem,
      PropertyDocumentDataGalleryItem,
      AllDocumentTypes,
    };
  }
}
